# Generated by Django 6.0.5 on 2026-05-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_provider_created_at_provider_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='distance',
        ),
        migrations.AddField(
            model_name='provider',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
