# Generated by Django 6.0.5 on 2026-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_remove_provider_distance_provider_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
