# Generated by Django 6.0.5 on 2026-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_profile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spotlight/')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
