# Generated by Django 6.0.5 on 2026-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Farminx Team', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
