# Generated by Django 6.0.5 on 2026-05-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_news_author_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collaborations/'),
        ),
    ]
