# Generated by Django 6.0.5 on 2026-05-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_collaboration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
