# Generated by Django 6.0.5 on 2026-05-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_address_latitude_address_longitude_order_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='worker_whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
